function observations = get_point_clusters(data,centroids)

% INPUT:
% data i x j
% centroids n x j

K = size(centroids,1);

for i = 1:size(data,1)
        temp = zeros(K,1);
        for n = 1:K
              temp(n) = sqrt( (centroids(n,1) - data(i,1))^2 + ...
              (centroids(n,2) - data(i,2))^2 + (centroids(n,3) - data(i,3))^2 + ...
              (centroids(n,4) - data(i,4))^2 + (centroids(n,5) - data(i,5))^2 + ...
              (centroids(n,6) - data(i,6))^2 + (centroids(n,7) - data(i,7))^2 + ...
              (centroids(n,8) - data(i,8))^2 + (centroids(n,9) - data(i,9))^2 + ...
              (centroids(n,10) - data(i,10))^2 + (centroids(n,11) - data(i,11))^2 + ...
              (centroids(n,12) - data(i,12))^2 + (centroids(n,13) - data(i,13))^2 + ...
              (centroids(n,14) - data(i,14))^2 + (centroids(n,15) - data(i,15))^2 + ...
              (centroids(n,16) - data(i,16))^2 + (centroids(n,17) - data(i,17))^2 + ...
              (centroids(n,18) - data(i,18))^2 + (centroids(n,19) - data(i,19))^2 + ...
              (centroids(n,20) - data(i,20))^2 + (centroids(n,21) - data(i,21))^2 + ...
              (centroids(n,22) - data(i,22))^2 + (centroids(n,23) - data(i,23))^2 + ...
              (centroids(n,24) - data(i,24))^2 + (centroids(n,25) - data(i,25))^2 + ...
              (centroids(n,26) - data(i,26))^2 + (centroids(n,27) - data(i,27))^2 + ...
              (centroids(n,28) - data(i,28))^2 + (centroids(n,29) - data(i,29))^2 + ...
              (centroids(n,30) - data(i,30))^2+...
                + (centroids(n,31) - data(i,31))^2 + ...
              (centroids(n,32) - data(i,32))^2 + (centroids(n,33) - data(i,33))^2 + ...
              (centroids(n,34) - data(i,34))^2 + (centroids(n,35) - data(i,35))^2 + ...
              (centroids(n,36) - data(i,36))^2 + (centroids(n,37) - data(i,37))^2 + ...
              (centroids(n,38) - data(i,38))^2 + (centroids(n,39) - data(i,39))^2 + ...
              (centroids(n,40) - data(i,40))^2 + (centroids(n,41) - data(i,41))^2 + ...
              (centroids(n,42) - data(i,42))^2 + (centroids(n,43) - data(i,43))^2 + ...
              (centroids(n,44) - data(i,44))^2 + (centroids(n,45) - data(i,45))^2 + ...
              (centroids(n,46) - data(i,46))^2 + (centroids(n,47) - data(i,47))^2 + ...
              (centroids(n,48) - data(i,48))^2 + (centroids(n,49) - data(i,49))^2 + ...
              (centroids(n,50) - data(i,50))^2 + (centroids(n,51) - data(i,51))^2 + ...
              (centroids(n,52) - data(i,52))^2 + (centroids(n,53) - data(i,53))^2 + ...
              (centroids(n,54) - data(i,54))^2 + (centroids(n,55) - data(i,55))^2 + ...
              (centroids(n,56) - data(i,56))^2 + (centroids(n,57) - data(i,57))^2 + ...
              (centroids(n,58) - data(i,58))^2 +(centroids(n,59) - data(i,59))^2+...
              (centroids(n,60) - data(i,60))^2 +(centroids(n,61) - data(i,61))^2 + ...
              (centroids(n,62) - data(i,62))^2 + (centroids(n,63) - data(i,63))^2 + ...
              (centroids(n,64) - data(i,64))^2 + (centroids(n,65) - data(i,65))^2 + ...
              (centroids(n,66) - data(i,66))^2 );
        end
        [id,I] = min(temp);
        observations(i,1) = I;
    end
end