function observations = get_point_clusters_shape(data,centroids)

% INPUT:
% data i x j
% centroids n x j

K = size(centroids,1);

for i = 1:size(data,1)
        temp = zeros(K,1);
        for n = 1:K
              temp(n) = sqrt( (centroids(n,1) - data(i,1))^2 + ...
              (centroids(n,2) - data(i,2))^2 + (centroids(n,3) - data(i,3))^2 + ...
              (centroids(n,4) - data(i,4))^2 + (centroids(n,5) - data(i,5))^2 + ...
              (centroids(n,6) - data(i,6))^2 + (centroids(n,7) - data(i,7))^2 + ...
              (centroids(n,8) - data(i,8))^2 + (centroids(n,9) - data(i,9))^2 + ...
              (centroids(n,10) - data(i,10))^2 + (centroids(n,11) - data(i,11))^2 + ...
              (centroids(n,12) - data(i,12))^2 + (centroids(n,13) - data(i,13))^2 + ...
              (centroids(n,14) - data(i,14))^2 + (centroids(n,15) - data(i,15))^2 + ...
              (centroids(n,16) - data(i,16))^2 + (centroids(n,17) - data(i,17))^2 + ...
              (centroids(n,18) - data(i,18))^2 + (centroids(n,19) - data(i,19))^2 + ...
              (centroids(n,20) - data(i,20))^2 + (centroids(n,21) - data(i,21))^2 + ...
              (centroids(n,22) - data(i,22))^2 + (centroids(n,23) - data(i,23))^2 + ...
              (centroids(n,24) - data(i,24))^2 );
        end
        [id,I] = min(temp);
        observations(i,1) = I;
    end
end